### ISSUE TITLE
LDtk Integrated Icons Cause Crashes

### ISSUE THREAD

**Issue by thisjaiden** [estivate/ldtk_rust#11]
*Description*
When loading a file that contains the use of LDtk's integrated icons, an error occurs with `serde_json`: "invalid type: null, expected a string at line x column y". As far as I can tell, this relates to the `relPath` field being null where it references integrated icons.

*Reproduction*
Create a ldtk project, create at least one thing that uses LDtk's integrated icons for its' editor representation, and export. You should find a tileset definition with `relPath` set to `null`. ([Example file attached](https://github.com/estivate/ldtk_rust/files/8500817/test.ldtk.txt))

*Potential Solution*
Use the new `embedAtlas` field to detect such cases and replace `relPath` with either a `Option<String>` or an enum between `String` and `LdtkIcons`.

**Comment by aleokdev** [comment]
This was fixed in the schema 21 days ago. PRing fix (1.1.3's schema)
![Screenshot_20220506_003039](https://user-images.githubusercontent.com/16354904/167035637-283694fa-48b9-4212-8817-245c0499c7d3.png)
